### ISSUE TITLE
Change quickSort to parallelSort

### ISSUE THREAD

**Issue by rdk** [rdk/FasterForest#2]
This is a single thread bottleneck on large datasets:
~~~"main" #1 prio=5 os_prio=0 tid=0x00007f40c800e000 nid=0x1c667 runnable [0x00007f40d0847000]
   java.lang.Thread.State: RUNNABLE
        at cz.siret.prank.fforest.FastRfUtils.partition(FastRfUtils.java:95)
        at cz.siret.prank.fforest.FastRfUtils.quickSort(FastRfUtils.java:123)
        at cz.siret.prank.fforest.FastRfUtils.quickSort(FastRfUtils.java:124)
~~~

**Comment by rdk** [comment]
Implemented in version 2.0.8
